language: node_js

node_js:
  - "0.10"

before_install: 
  - npm install -g grunt-cli
  - ruby --version
  - bundle install
  # Need to add the repo to get php v5.5, currently it defaults to 5.3
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:ondrej/php5
  - sudo apt-get update
  - sudo apt-get install php5 curl
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install
  - npm install grunt-phpcs
  - ./vendor/bin/phpcs -vvv -w --config-set installed_paths "../../../coding_standards/"

install: npm install